[package]
name = "liorforth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.small]
inherits = "release"
opt-level = "z"
strip = "symbols"
panic = "abort"
lto = true
codegen-units = 1